#!/usr/bin/env perl
use Mojolicious::Lite;

use Mojo::Util 'monkey_patch';

plugin 'Log::Timestamp';
plugin 'Log::Access';
app->log->level('info');
@{app->static->paths} = ''. app->home;

# This is CORS-open; need to restrict allowed origin
helper cors_headers => sub {
  my $c = shift;
  $c->res->headers
#    ->header('Access-Control-Allow-Origin' => '*')
    ->header('Access-Control-Allow-Credentials' => 'true')
    ->header('Access-Control-Allow-Methods' => join ', ', qw(OPTIONS POST))
    ->header('Access-Control-Allow-Headers' => join ', ',
        qw(Content-Type X-CSRF-Token X-Requested-With))
    ->header('Access-Control-Max-Age' => '1728000');
  return $c;
};

options '*' => sub { shift->cors_headers->render(data => '', status => 200) };
post '/api/upload' => sub {
    shift->cors_headers->render(data => '', status => 200) };

get '/' => sub { shift->redirect_to('demo/index.html') };

app->secrets(['change me'])->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'File Upload';
<h1>Mojolicious backend demo for ng2-es5-file-upload</h1>

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>
